/*
 * dosbox_bridge.h - Plain-C-ABI header for the DOSBox-X offscreen core bridge.
 *
 * No JNI, no C++ types, no SDL types in the signatures. Meant to be called
 * from dart:ffi, and (via a thin shim) from Java/Kotlin or Swift.
 *
 * WHY THIS CAN EXIST
 * ------------------
 * DOSBox-X already has an offscreen render backend: the "Game Link" output
 * (SCREEN_GAMELINK, src/output/output_gamelink.cpp), built for external
 * clients like Grid Cartographer. In that mode DOSBox-X:
 *
 *   - hands render.cpp a plain malloc'd 32-bit framebuffer instead of an SDL
 *     surface (OUTPUT_GAMELINK_StartUpdate -> sdl.gamelink.framebuf),
 *   - publishes the finished frame to an external consumer
 *     (OUTPUT_GAMELINK_Transfer),
 *   - accepts mouse and keyboard state from that consumer and injects it via
 *     MAPPER_CheckEvent / Mouse_* (OUTPUT_GAMELINK_InputEvent),
 *   - and is guarded out of SDL's own window/input event handling by the
 *     `if (sdl.desktop.type == SCREEN_GAMELINK) break;` cases scattered
 *     through sdlmain.cpp.
 *
 * This bridge is a SCREEN_FLUTTER output modelled on SCREEN_GAMELINK, with
 * the shared-memory mmap replaced by an in-process buffer this header hands
 * out directly. That is the whole trick: we are not writing a new renderer,
 * we are re-pointing an existing, upstream-maintained one.
 *
 * PIXEL FORMAT
 * ------------
 * Frames are 32bpp, one uint32_t per pixel, in the same format Game Link
 * uses -- see GFX_GetRGB's SCREEN_GAMELINK case in sdlmain.cpp:
 *
 *     (blue << 0) | (green << 8) | (red << 16) | (255 << 24)
 *
 * i.e. 0xAARRGGBB as a little-endian uint32_t, which is B,G,R,A in memory
 * order. That is exactly Flutter's ui.PixelFormat.bgra8888, so Dart can hand
 * the bytes to decodeImageFromPixels with no conversion pass.
 *
 * THREADING
 * ---------
 * DOSBox-X's mainloop owns essentially all emulator state and is not
 * thread-safe. It runs on its own pthread, started by dosbox_core_start().
 * Every function here that mutates emulator state is therefore either
 *   (a) an atomic flag the mainloop reads, or
 *   (b) a mailbox request the mainloop drains at a frame boundary,
 * never a direct call into the core. Functions documented as SYNCHRONOUS
 * block the caller on a condvar until the mainloop reports back.
 */
#ifndef DOSBOX_MULTIPLATFORM_DOSBOX_BRIDGE_H
#define DOSBOX_MULTIPLATFORM_DOSBOX_BRIDGE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------------ */
/* Result codes                                                             */
/* ------------------------------------------------------------------------ */

#define DOSBOX_OK 0
#define DOSBOX_ERR (-1)

/* The mainloop did not service a mailbox request within its timeout. */
#define DOSBOX_ERR_TIMEOUT (-2)

/* The core is not running, so the request is meaningless. */
#define DOSBOX_ERR_NOT_RUNNING (-3)

/* The core is already running a session. After a successful
 * dosbox_core_stop() a new start() is allowed. */
#define DOSBOX_ERR_ALREADY_STARTED (-4)

/* ------------------------------------------------------------------------ */
/* Lifecycle                                                                */
/* ------------------------------------------------------------------------ */

/*
 * Point the core at its resource directory -- the tree holding DOSBox-X's
 * own data files (fonts, translations, the shipped dosbox-x.conf template,
 * glshaders/). On Android this is an assets/ subtree extracted to real files
 * at first launch, because the core opens these by path.
 *
 * Must be called before dosbox_core_start().
 */
void dosbox_core_init(const char *resource_dir);

/*
 * Start the DOSBox-X mainloop on a background thread using the config file
 * at conf_path.
 *
 * conf_path is a full dosbox-x.conf generated by the Dart side (see
 * lib/services/dos_config.dart, ported from the Java GameLauncherActivity's
 * buildConf/mountLines). It is the ONLY channel by which a title is
 * launched: mounts, machine type, cycles, and the [autoexec] that runs the
 * program all live in that file. There is deliberately no "start this game"
 * argument here.
 *
 * Returns DOSBOX_OK if the thread was started, DOSBOX_ERR_ALREADY_STARTED if
 * a core is already up. Asynchronous: the machine is still booting when this
 * returns. Poll dosbox_core_is_running() / dosbox_core_get_framebuffer().
 */
int32_t dosbox_core_start(const char *conf_path);

/*
 * Shut the machine down and tear the engine down with it.
 *
 * Queues the same kill switch DOSBox-X's own Ctrl+F9 uses (an exception
 * thrown on the mainloop thread out of DOSBOX_RunMachine), which makes
 * dosbox_x_main run its full teardown and return. Blocks (bounded, ~5s)
 * until the mainloop thread has exited, then resets the bridge so a later
 * dosbox_core_start() begins a genuinely new session with a new conf.
 *
 * Returns DOSBOX_OK on a clean teardown, DOSBOX_ERR if nothing was running
 * or the mainloop did not exit in time (callers should then fall back to a
 * process restart, which is all the Android app this replaces had anyway).
 */
int32_t dosbox_core_stop(void);

/* 1 if the mainloop is running, 0 otherwise. */
int32_t dosbox_core_is_running(void);

/* Gate the mainloop. Paused means no CPU emulation and no new frames, but
 * the framebuffer keeps its last contents so the UI can still display it. */
void dosbox_core_set_paused(int32_t paused);

/* ------------------------------------------------------------------------ */
/* Video                                                                    */
/* ------------------------------------------------------------------------ */

/*
 * Return a pointer to the internal 32bpp framebuffer (owned by the bridge;
 * do not free). out_width/out_height receive the current frame dimensions,
 * out_pitch_bytes the row stride in BYTES -- DOSBox-X's render pitch is not
 * always width*4, so callers must honour it rather than assuming.
 *
 * Returns NULL until the first frame has been rendered.
 *
 * The mainloop overwrites this buffer in place on its own thread, so the
 * caller must COPY the pixels it wants before yielding. See
 * DosboxCoreBindings.getFramebuffer() in Dart, which does exactly that.
 */
/* ------------------------------------------------------------------------ */
/* Shared frames, for running the engine in another process               */
/* ------------------------------------------------------------------------ */

/*
 * Publish finished frames into a file both processes map, instead of a buffer
 * private to this one.
 *
 * The engine runs in its own process because DOSBox-X is a one-shot core: it
 * has no teardown path, so ending a session has to mean ending a process. But
 * the launcher still wants to DRAW the picture, inside its own window,
 * alongside its own controls -- and a pointer from another process is worth
 * nothing to it.
 *
 * So the frame goes somewhere both can see. The mapping is a header followed
 * by pixels, and the header carries everything the reader needs (size, pitch,
 * frame counter), which means there is no per-frame IPC at all: the reader
 * polls the mapping exactly as an in-process reader polls
 * dosbox_core_get_framebuffer, and a frame counter that has not moved costs
 * it nothing.
 *
 * Call before dosbox_core_start(). Returns DOSBOX_OK, or DOSBOX_ERR if the
 * file cannot be created or mapped -- in which case the caller should fall
 * back to the in-process path rather than run a session nobody can see.
 */
int32_t dosbox_core_set_shared_frame(const char *path, int32_t max_width,
                                     int32_t max_height);

/*
 * Attach to a mapping another process is publishing into, read-only.
 *
 * The reader side of the above, and the whole reason this lives in the same
 * library: the launcher already links libdosboxcore for its own in-process
 * path, so reading a shared frame needs no second artifact. Loading the
 * library does not start an engine.
 */
int32_t dosbox_shared_frame_attach(const char *path);

/*
 * The attached mapping's current frame, in the shape
 * dosbox_core_get_framebuffer returns, so a reader can use either without
 * caring which. Returns NULL when nothing is attached or no frame has landed.
 */
const uint32_t *dosbox_shared_frame_get(int32_t *out_width, int32_t *out_height,
                                        int32_t *out_pitch_bytes);

/* The attached mapping's frame counter, for skipping unchanged frames. */
uint64_t dosbox_shared_frame_counter(void);

void dosbox_shared_frame_detach(void);

const uint32_t *dosbox_core_get_framebuffer(int32_t *out_width,
                                            int32_t *out_height,
                                            int32_t *out_pitch_bytes);

/*
 * Monotonically increasing counter, bumped once per completed frame. Lets
 * the UI skip the copy+decode entirely when nothing has changed, which
 * matters a lot: DOS text mode may sit on an identical frame for seconds.
 */
uint64_t dosbox_core_get_frame_counter(void);

/* The aspect ratio DOSBox-X says this frame should be displayed at
 * (render.src.ratio). Returned x1000 to keep the ABI integer-only; e.g.
 * 1200 means 1.2. 0 if unknown. Needed because DOS modes are frequently
 * non-square-pixel (320x200 is a 4:3 display, not 16:10). */
int32_t dosbox_core_get_pixel_aspect_x1000(void);

/* ------------------------------------------------------------------------ */
/* Input                                                                    */
/* ------------------------------------------------------------------------ */

/*
 * Keyboard, by SDL2 scancode (SDL_SCANCODE_*). Injected through
 * MAPPER_CheckEvent exactly as the Game Link path does, so DOSBox-X's own
 * key mapper, and therefore every DOS program, sees a normal key.
 *
 * Scancodes rather than characters on purpose: DOS games read the keyboard
 * at the scancode level and a character-based API cannot express e.g. the
 * difference between the two Alt keys, or a held arrow key.
 */
void dosbox_core_key_event(int32_t sdl_scancode, int32_t pressed);

/* Relative mouse motion, in emulated-screen pixels. */
void dosbox_core_mouse_motion(int32_t dx, int32_t dy);

/*
 * Absolute mouse position as a fraction of the frame, x1000 (0..1000). Used
 * for touch-to-point on a tablet, where there is no relative motion to
 * report. DOSBox-X's mouse emulation prefers relative input, so this is a
 * convenience that the bridge converts to deltas.
 */
void dosbox_core_mouse_position(int32_t x_per_mille, int32_t y_per_mille);

/* button: 0 left, 1 right, 2 middle. */
void dosbox_core_mouse_button(int32_t button, int32_t pressed);

/*
 * Emulated PC joystick/gamepad state.
 *
 * port: 0 or 1. mask: bitwise OR of DOSBOX_JOY_*. axis_x/axis_y: -1000..1000
 * analog position, for games that read a proportional stick rather than
 * digital directions.
 */
#define DOSBOX_JOY_UP 0x01
#define DOSBOX_JOY_DOWN 0x02
#define DOSBOX_JOY_LEFT 0x04
#define DOSBOX_JOY_RIGHT 0x08
#define DOSBOX_JOY_BUTTON1 0x10
#define DOSBOX_JOY_BUTTON2 0x20
#define DOSBOX_JOY_BUTTON3 0x40
#define DOSBOX_JOY_BUTTON4 0x80

void dosbox_core_joystick(int32_t port, int32_t mask, int32_t axis_x,
                          int32_t axis_y);

/*
 * Type a line into the DOS shell as if the user had typed it, then press
 * Enter. Convenience for the UI's "run this program" / "mount this CD"
 * actions after boot; goes through the same keyboard buffer as real typing.
 */
int32_t dosbox_core_send_command(const char *line);

/* ------------------------------------------------------------------------ */
/* Save states                                                              */
/* ------------------------------------------------------------------------ */

/*
 * DOSBox-X's own save state machinery (class SaveState in include/dosbox.h)
 * is slot-based, not path-based: slots [0, DOSBOX_SLOT_COUNT). These wrap
 * SaveState::instance().save()/load(), which must run on the mainloop
 * thread, so both are SYNCHRONOUS via mailbox and may return
 * DOSBOX_ERR_TIMEOUT.
 *
 * The Dart SaveStateService layers its own naming, thumbnails and eviction
 * on top of these slots (see lib/services/save_state_service.dart).
 */
#define DOSBOX_SLOT_COUNT 10

int32_t dosbox_core_save_state(int32_t slot);
int32_t dosbox_core_load_state(int32_t slot);

/* 1 if the slot holds a state, 0 if empty, <0 on error. */
int32_t dosbox_core_state_is_empty(int32_t slot);

/* ------------------------------------------------------------------------ */
/* Live configuration                                                       */
/* ------------------------------------------------------------------------ */

/*
 * Reflection over DOSBox-X's config system, so the settings UI is generated
 * from the engine's real property list rather than a hand-maintained
 * duplicate. This is a direct port of the JNI bridge the Java app used
 * (native/patches/0007-android-native-config-gui.patch in the old repo),
 * with JNI string returns replaced by caller-supplied buffers.
 *
 * Every getter follows the same convention: it writes at most buf_len bytes
 * (always NUL-terminated) into buf and returns the number of bytes the full
 * answer WOULD have needed. A return >= buf_len means the caller should
 * retry with a bigger buffer. Returns <0 on error.
 */

/* Newline-separated list of section names ("sdl", "dosbox", "cpu", ...). */
int32_t dosbox_core_config_sections(char *buf, int32_t buf_len);

/*
 * JSON array describing one section's properties, each object having:
 *   name, type ("bool"|"int"|"string"|"hex"|"double"), value, default,
 *   help, values[] (the legal set, empty if unconstrained).
 * The UI uses `type` and `values` to pick a widget.
 */
int32_t dosbox_core_config_section_properties(const char *section, char *buf,
                                             int32_t buf_len);

/* Apply a property to the RUNNING engine. Returns DOSBOX_OK on success. */
int32_t dosbox_core_config_set(const char *section, const char *property,
                               const char *value);

/* Write the running config back out to the active .conf file. */
int32_t dosbox_core_config_save(void);

/* ------------------------------------------------------------------------ */
/* Status                                                                   */
/* ------------------------------------------------------------------------ */

/* Measured frames per second of the render callback. */
int32_t dosbox_core_get_fps(void);

/* Smoothed 0..100 output audio peak, for level meters. */
int32_t dosbox_core_get_audio_level(void);

/* Emulated CPU speed in cycles, as the status line reports it. */
int32_t dosbox_core_get_cycles(void);

/*
 * The name of the DOS program currently executing (DOSBox-X's
 * RunningProgram), e.g. "DOOM". Same buffer convention as the config
 * getters. Useful for the UI to label the session and to auto-detect which
 * title a save state belongs to.
 */
int32_t dosbox_core_get_running_program(char *buf, int32_t buf_len);

/*
 * DOSBox-X's status line text (what GFX_SetTitle would have put in the
 * window caption: fps, cycles, paused state). Same buffer convention.
 */
int32_t dosbox_core_get_status_line(char *buf, int32_t buf_len);

#ifdef __cplusplus
}
#endif

#endif /* DOSBOX_MULTIPLATFORM_DOSBOX_BRIDGE_H */
