package com.crownpark.retrodosbox

import android.os.Bundle
import org.libsdl.app.SDLActivity

/**
 * The emulator, in a process of its own.
 *
 * DOSBox-X is a one-shot core: its upstream globals have no complete teardown
 * path, so a second start in the same process is unsafe, and the Quit that
 * dosbox_core_stop queues is delivered through the frame-publish hook, which a
 * core that has stopped rendering never reaches. Embedded in the launcher's
 * process, that left exactly one usable session per app launch -- and closing
 * a game wedged the core rather than freeing it.
 *
 * Running it here instead means ending a session is ending a PROCESS. Android
 * reclaims everything the engine leaked, the launcher is untouched, and the
 * next game starts in a genuinely fresh core. This is the arrangement
 * Retro-Amiga uses for its own core in :sdl, for the same reason.
 *
 * Why SDLActivity rather than the bridge's offscreen path: libdosboxcore
 * exports SDL_main, and libSDL2 carries the whole Android video backend, so
 * SDL can own a window here and DOSBox-X can render straight into this
 * activity's SurfaceView. Nothing has to cross a process boundary -- no shared
 * framebuffer, no IPC per input event. The launcher's in-process FFI path
 * exists for desktop and stays where it is.
 */
class DosboxEmulatorActivity : SDLActivity() {

    /**
     * SDL first, then the core: libdosboxcore's SDL symbols are resolved
     * against libSDL2, and loading it first leaves them undefined.
     */
    override fun getLibraries(): Array<String> = arrayOf("SDL2", "dosboxcore")

    /**
     * The same command line the in-process bridge builds, because it is the
     * same engine reading it: one conf per title, generated by the launcher.
     *
     * A missing conf is not survivable -- DOSBox-X would boot a bare machine
     * with no mounts and no autoexec, which looks like a game that failed to
     * start rather than a launcher that forgot to say which one.
     */
    override fun getArguments(): Array<String> {
        val conf = intent?.getStringExtra(EXTRA_CONF_PATH)
        if (conf.isNullOrEmpty()) return emptyArray()
        return arrayOf("-conf", conf)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (intent?.getStringExtra(EXTRA_CONF_PATH).isNullOrEmpty()) {
            // Nothing to run. Leaving the activity up would show a bare DOS
            // prompt the user did not ask for.
            finish()
        }
    }

    companion object {
        const val EXTRA_CONF_PATH = "conf_path"
    }
}
